import Head from 'next/head'
import {
  Button,
  Container,
} from '../components/sharedstyles'

import styled, { ThemeConsumer } from 'styled-components'
import Link from 'next/link'
import Navbar from '../components/Navbar'
import Footer from '../components/Footer'


const Header = styled.header`
    /* position: fixed; */
    width: 70vw;
    display: flex;
    top: 0;
    /* left: 50%; */
    /* translate: -50%; */
    gap: 2em;
    /* padding: 1rem; */
    color: ${({ theme }) => theme.colors.white[400]};
    justify-content: center;
    align-items: center;
    min-width: 700px;
    margin-bottom: 3rem;

  .box{
    margin: 0 auto;
    display: flex;
    flex-direction: row;
    gap: 1.5rem;
    width: max-content;

    a{
      text-decoration: none;
      padding: 1rem 0;
      
      &:hover{
        color: white;
      }
    }

  }
`

const LayoutWidth = styled.div`
    width: 70vw;
    min-width: 700px;
`



const addSaturation = (color: any, amount: number) => {
  var color = color.replace('#', '').split('');
  var letters = '0123456789ABCDEF'.split('');
  for(var i = 0; i < color.length; i++){
      var newSaturation = 0;
      if(letters.indexOf(color[i]) + amount > 15) newSaturation = 15;
      else if(letters.indexOf(color[i]) + amount < 0) newSaturation = 0;
      else newSaturation = letters.indexOf(color[i]) + amount;
      color[i] = letters[newSaturation];
  }
  return "#" + color.join('');
}


const TopBar = styled.div`
  width: 100%;
  position: relative;
  /* background: ${({ theme }) => theme.colors.white[400]}; */
  background: ${({theme}) => theme.colors.primary};
  `

const About = styled.div`
  width: 100%;
  background: ${({ theme }) => theme.colors.white[100]};
  outline: solid ${({ theme }) => theme.colors.white[200]} 2px;
  border-radius: 20px;
  /* box-sizing: border-box; */

  /* height: 100px; */
  display: flex;
  /* justify-content: center; */
    align-items: center;
  /* flex-direction: column; */
  padding: 2rem 2rem 4rem 2rem;

  .title{
    margin-right: auto;
  }

  a,h1,h2{
    width: max-content;
    margin: 0;
  }

  &:hover{
    background: ${({ theme }) => theme.colors.white[200]};
  }
  
`

const Content = styled.div`
  width: 50%;
  display: flex;
  flex-direction: column;
  gap: 2rem;
  color: ${({ theme }) => theme.colors.white[500]};
  line-height: 1.4;

  h2{
    color: ${({ theme }) => theme.colors.white[600]};
    margin: 0;
    font-weight: 500;
  }

  li {counter-increment: li}

  
  li::before {content: counter(li)" · "; color: ${({ theme }) => theme.colors.white[600]};
  display: inline-block; width: 1.3em;
  margin-left: -1em}

ol{
  list-style: none;
  counter-reset: (li);
  margin: 0;
  padding: 0.5rem 0 0.5rem 1rem;
}

img{
  border-radius: 20px;
}


  p{
    margin: 0.5rem 0 0.5rem 0;
  }

`

const Title = styled.div`
      width: 50%;
      display: flex;
      flex-direction: column;

      p,a{
        color: ${({ theme }) => theme.colors.white[400]};
      }


`

export default function Home() {

  return (
    <>
    <Head>
        <title>Canpit</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.png" />
    </Head>
    <Container>
        <TopBar>
          <p style={{color: 'black', textAlign: 'center', fontSize: '0.8em', margin: '0.7em', fontWeight: 500}}>PRE BETA ACCESS</p>
        </TopBar>
      <LayoutWidth>

      <Navbar></Navbar>

      <div style={{display: 'flex', gap: '3rem'}}>

        <Title>
          <h1 style={{fontSize: '3rem', margin: '0 0 auto 0', position: 'sticky', top: '2rem'}}>With mission to simplify conversations.</h1>
          <p>This project is in development as part of a final project in high school to obtain a high school diploma.</p>
        </Title>

        <Content>
            <div>
              <h2>Introduction</h2>
              <p>Canpit is web-based video chatting platform for groups of all kinds but specifically focused on groups speaking foreign languages. Created with mission to engage participants with activities and smooth-out conversations.</p>
            </div>
            <div>
              <h2>Main objectives</h2>
              <ol>
                <li>Engage all participants during conversation</li>
                <li>Smooth out conversation and make it easier</li>
                <li>Create playful integrated activities/games</li>
              </ol>
            </div>
            <div>
              <h2>Prototyping & Development</h2>
              <p>In devlepomnet since summer of 2022. Project is in early stage.</p>
              <div style={{display: 'flex', flexDirection: 'column', gap: '0.5rem'}}>
                <img src="/img/prototype5.png" alt="" style={{width: '100%'}} />
                {/* <img src="/img/prototype4.png" alt="" style={{width: '100%'}} /> */}
                {/* <img src="/img/prototype2.jpg" alt="" style={{width: '100%'}} /> */}
              </div>
              <p>... just beginning</p>
            </div>
        </Content>

      </div>

      <Footer/>

      </LayoutWidth>
    </Container>

    </>
  )
}