//@ts-nocheck
import Head from 'next/head'
import {
  ActivityThnail,
  Button,
  Container,
  Title
} from '../components/sharedstyles'

import styled, { ThemeConsumer } from 'styled-components'
import Link from 'next/link'
import Navbar from '../components/Navbar'
import Footer from '../components/Footer'
import { activitiesList as list } from '../components/acitivies/list';


const LayoutWidth = styled.div`
    width: 70vw;
    min-width: 700px;
`

const addSaturation = (color: any, amount: number) => {
  var color = color.replace('#', '').split('');
  var letters = '0123456789ABCDEF'.split('');
  for(var i = 0; i < color.length; i++){
      var newSaturation = 0;
      if(letters.indexOf(color[i]) + amount > 15) newSaturation = 15;
      else if(letters.indexOf(color[i]) + amount < 0) newSaturation = 0;
      else newSaturation = letters.indexOf(color[i]) + amount;
      color[i] = letters[newSaturation];
  }
  return "#" + color.join('');
}


const TopBar = styled.div`
  width: 100%;
  position: relative;
  /* background: ${({ theme }) => theme.colors.white[400]}; */
  background: ${({theme}) => theme.colors.primary};
  `

const About = styled.div`
  width: 100%;
  background: ${({ theme }) => theme.colors.white[100]};
  outline: solid ${({ theme }) => theme.colors.white[200]} 2px;
  border-radius: 20px;
  /* box-sizing: border-box; */

  /* height: 100px; */
  display: flex;
  /* justify-content: center; */
    align-items: center;
  /* flex-direction: column; */
  padding: 2rem 2rem 4rem 2rem;

  .title{
    margin-right: auto;
  }

  a,h1,h2{
    width: max-content;
    margin: 0;
  }

  &:hover{
    background: ${({ theme }) => theme.colors.white[200]};
  }
  
`

const Content = styled.div`
  width: 50%;
  display: flex;
  flex-direction: column;
  gap: 2rem;
  color: ${({ theme }) => theme.colors.white[500]};
  /* margin-top: 190px; */

  h2{
    color: ${({ theme }) => theme.colors.white[600]};
    margin: 0 0 2rem 0;
    font-weight: 500;
  }

  p{
    margin: 0.5rem 0 0 0;
  }

  div{

  }
`

const Icon = styled.div`
      height: 80px;
      width: 80px;
      background-color: ${props => props.color};
      border-radius: 10px;
      cursor: pointer;

      /* {position: 'absolute', top: '50%', left: '50%', transform: 'translate(calc(-25vw - 50%), -50%)' } */

`



export default function Home() {

  return (
    <>
    <Head>
        <title>Canpit</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.png" />
    </Head>
    <Container>
        <TopBar>
          <p style={{color: 'black', textAlign: 'center', fontSize: '0.8em', margin: '0.7em', fontWeight: 500}}>PRE BETA ACCESS</p>
        </TopBar>
      <LayoutWidth>

      <Navbar></Navbar>

      <div style={{display: 'flex', gap: '3rem'}}>
        <div style={{width: '50%', display: 'flex', flexDirection: 'column',}}>
          <h1 style={{fontSize: '3rem', margin: '0 0 auto 0', position: 'sticky', top: '2rem'}}>Library of Ativities you can play.</h1>
        </div>
     
        <Content>
            <div>
              <h2>Comming soon</h2>
              <div style={{display: 'flex', flexWrap: 'wrap', gap: '1rem'}}>
              {
                Object.keys(list).map((a, i) =>
                <ActivityThnail color={list[a].color} key={i}>
                    <Icon color={list[a].color}/>
                    <h3>{list[a].title}</h3>
                    <p>{list[a].desc.substring(0, 32)}...</p>
                  </ActivityThnail>
                )
              }
              </div>
            </div>
        </Content>

      </div>


      </LayoutWidth>
    </Container>
      <Footer/>

    </>
  )
}