import Head from 'next/head'
import {
  Button,
  Container,
  Title
} from '../components/sharedstyles'

import styled from 'styled-components'
import Link from 'next/link'


const Header = styled.header`
    position: fixed;
    width: 70vw;
    display: flex;
    top: 0;
    left: 50%;
    translate: -50%;
    gap: 2em;
    padding: 1rem;
    color: ${({ theme }) => theme.colors.white[300]};
    justify-content: center;
    align-items: center;
    min-width: 700px;

  .box{
    margin: 0 auto;
    display: flex;
    flex-direction: row;
    gap: 1.5rem;
    width: max-content;

    a{
      text-decoration: none;
      padding: 1rem 0;
      
      &:hover{
        color: white;
      }
    }

  }
`

const LayoutWidth = styled.div`
    width: 70vw;
    min-width: 700px;
`

const CTA = styled.a`
  color: ${({ theme }) => theme.colors.black[300]};
  font-family: inherit;
  background-color: ${({ theme }) => theme.colors.primary};
  width: max-content;
  padding: 8px 12px 9px 12px;
  font-weight: 500;
  border-radius: 7px;
  font-size: 1rem;
  border: none;
  transition: background-color 150ms;
  text-decoration: none;
  
  &.max{
    color: ${({ theme }) => theme.colors.black[300]};
    padding: 12px 16px 12px 16px;
    border-radius: 10px;
    font-size: 1.2rem;
  }
  
  &:hover,:active,:focus {
    background-color: ${({theme}) => addSaturation(theme.colors.primary, 2)};
    cursor: pointer;
  } 
`

const addSaturation = (color: any, amount: number) => {
  var color = color.replace('#', '').split('');
  var letters = '0123456789ABCDEF'.split('');
  for(var i = 0; i < color.length; i++){
      var newSaturation = 0;
      if(letters.indexOf(color[i]) + amount > 15) newSaturation = 15;
      else if(letters.indexOf(color[i]) + amount < 0) newSaturation = 0;
      else newSaturation = letters.indexOf(color[i]) + amount;
      color[i] = letters[newSaturation];
  }
  return "#" + color.join('');
}

// const Wave = styled.p`
//   width: 100%;
//   color: transparent;
//   text-decoration-line: underline;
//   text-decoration-style: wavy;
//   text-decoration-color: red;
// `

// const Photos = styled.div`
//   position: absolute;
//   background-color: red;
//   height: 40vh;
//   width: 50vw;
//   margin: 5rem auto;
//   left: 50%;
//   translate: -50%;
//   background-position: center;
//   background-size: ;
//   background-repeat: no-repeat;
//   transition: none;
//   animation: ph 5s infinite;

//   @keyframes ph {
//     0%   {  background-image: url('/image 54.png');}
//     25%  {  background-image: url('/image 55.png');}
//     50%  {  background-image: url('/image 56.png');}
//     75%  {  background-image: url('/image 58.png');}
//     100% {  background-image: url('/image 54.png');}
//   }
// `

// const Photos = styled.img`
//   position: absolute;
//   translate: 50% -40%;
//   /* filter: grayscale(50%); */
//   /* mix-blend-mode: color; */

// `




export default function Home() {
    //   const [img, setImg] = useState<string>('image 58.png');
    // const makeTimer = (counter: number) => {
    //       console.log(counter);
    //       const imgs = ['image 54.png', 'image 55.png', 'image 56.png', 'image 58.png']
    //       setImg(imgs[counter])
    //       counter = (counter === 3) ? 0 : counter++

    //       setTimeout(makeTimer(counter), 2000)
    // }

  return (
    <>
    <Head>
        <title>Canpit</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.png" />
    </Head>
    <Container>
      <LayoutWidth>
        <Header>
          <h2>Canpit</h2>

          <div className='box'>
          <Link href={'/'}>Activities</Link>
          <Link href={'/'}>How it works?</Link>
          <Link href={'/'}>Donate</Link>
          <Link href={'/'}>About</Link>
          </div>

          {/* <div className='box'> */}
            <Link href='/app'>
            <CTA>Jump into conversation</CTA>
            </Link>
          {/* </div> */}
        </Header>

          {/* <div> */}
            {/* <Title>Place for <Playfull>playfull</Playfull> conversations</Title> */}
            <Title>
                <img src="/img/homeTitle.svg" style={{width: '100%'}}/>
            </Title>
            {/* <CTA className='max'>Setup my room</CTA> */}
            {/* Place for playfull conversations that you forget time */}
          {/* </div> */}
      </LayoutWidth>
    </Container>

    </>
  )
}